services:
  # aws-emulator:
  #   build: .
  #   networks:
  #     - awsland
  #   ports:
  #     - "5050:8080"

  openscad-health:
    build:
      context: ./
      dockerfile: ./openscad/.
    image: openscad
    command: openscad.health
    ports:
      - "5051:8080"

  openscad-preview:
    image: openscad
    # build: ./openscad/.
    command: openscad.preview
    # networks:
    #   - awsland
    ports:
      - "5052:8080"

  openscad-stl:
    image: openscad
    # build: ./openscad/.
    command: openscad.stl
    ports:
      - "5053:8080"

  cadquery-stl:
    build:
      context: ./
      dockerfile: ./cadquery/.
    command: cadquery.stl
    ports:
      - 5060:8080

# networks:
#   awsland:
#     name: awsland
