services:
  # aws-emulator:
  #   build: .
  #   networks:
  #     - awsland
  #   ports:
  #     - "5050:8080"

  openscad-health:
    build:
      context: ./
      dockerfile: ./openscad/.
    image: openscad
    command: openscad.health
    ports:
      - "5051:8080"

  openscad-preview:
    image: openscad
    # build: ./openscad/.
    command: openscad.preview
    # networks:
    #   - awsland
    ports:
      - "5052:8080"
    environment:
      AWS_SECRET_ACCESS_KEY: "${DEV_AWS_SECRET_ACCESS_KEY}"
      AWS_ACCESS_KEY_ID: "${DEV_AWS_ACCESS_KEY_ID}"
      BUCKET: "${DEV_BUCKET}"

  openscad-stl:
    image: openscad
    # build: ./openscad/.
    command: openscad.stl
    ports:
      - "5053:8080"
    environment:
      AWS_SECRET_ACCESS_KEY: "${DEV_AWS_SECRET_ACCESS_KEY}"
      AWS_ACCESS_KEY_ID: "${DEV_AWS_ACCESS_KEY_ID}"
      BUCKET: "${DEV_BUCKET}"

  cadquery-stl:
    build:
      context: ./
      dockerfile: ./cadquery/.
    command: cadquery.stl
    ports:
      - 5060:8080
    environment:
      AWS_SECRET_ACCESS_KEY: "${DEV_AWS_SECRET_ACCESS_KEY}"
      AWS_ACCESS_KEY_ID: "${DEV_AWS_ACCESS_KEY_ID}"
      BUCKET: "${DEV_BUCKET}"

# networks:
#   awsland:
#     name: awsland
